import type { InstrumentName } from "soundfont-player";

export const Instruments: Record<InstrumentName, string> = {
  accordion: "Accordion",
  acoustic_bass: "Acoustic Bass",
  acoustic_grand_piano: "Acoustic Grand Piano",
  acoustic_guitar_nylon: "Acoustic Nylon Guitar",
  acoustic_guitar_steel: "Acoustic Steel Guitar",
  agogo: "Agogo",
  alto_sax: "Alto Sax",
  applause: "Applause",
  bagpipe: "Bagpipe",
  banjo: "Banjo",
  baritone_sax: "Baritone Sax",
  bassoon: "Bassoon",
  bird_tweet: "Bird Tweet",
  blown_bottle: "Blown Bottle",
  brass_section: "Brass Section",
  breath_noise: "Breath Noise",
  bright_acoustic_piano: "Bright Acoustic Piano",
  celesta: "Celesta",
  cello: "Cello",
  choir_aahs: "Choir (Aahs)",
  church_organ: "Church Organ",
  clarinet: "Clarinet",
  clavinet: "Clavinet",
  contrabass: "Contrabass",
  distortion_guitar: "Distortion Guitar",
  drawbar_organ: "Drawbar Organ",
  dulcimer: "Dulcimer",
  electric_bass_finger: "Electric Bass (Finger)",
  electric_bass_pick: "Electric Bass (Pick)",
  electric_grand_piano: "Electric Grand Piano",
  electric_guitar_clean: "Electric Guitar (Clean)",
  electric_guitar_jazz: "Electric Guitar (Jazz)",
  electric_guitar_muted: "Electric Guitar (Muted)",
  electric_piano_1: "Electric Piano 1",
  electric_piano_2: "Electric Piano 2",
  english_horn: "english_horn",
  fiddle: "fiddle",
  flute: "flute",
  french_horn: "french_horn",
  fretless_bass: "fretless_bass",
  fx_1_rain: "fx_1_rain",
  fx_2_soundtrack: "fx_2_soundtrack",
  fx_3_crystal: "fx_3_crystal",
  fx_4_atmosphere: "fx_4_atmosphere",
  fx_5_brightness: "fx_5_brightness",
  fx_6_goblins: "fx_6_goblins",
  fx_7_echoes: "fx_7_echoes",
  fx_8_scifi: "fx_8_scifi",
  glockenspiel: "glockenspiel",
  guitar_fret_noise: "guitar_fret_noise",
  guitar_harmonics: "guitar_harmonics",
  gunshot: "gunshot",
  harmonica: "harmonica",
  harpsichord: "harpsichord",
  helicopter: "helicopter",
  honkytonk_piano: "honkytonk_piano",
  kalimba: "kalimba",
  koto: "koto",
  lead_1_square: "lead_1_square",
  lead_2_sawtooth: "lead_2_sawtooth",
  lead_3_calliope: "lead_3_calliope",
  lead_4_chiff: "lead_4_chiff",
  lead_5_charang: "lead_5_charang",
  lead_6_voice: "lead_6_voice",
  lead_7_fifths: "lead_7_fifths",
  lead_8_bass__lead: "lead_8_bass__lead",
  marimba: "marimba",
  melodic_tom: "melodic_tom",
  music_box: "music_box",
  muted_trumpet: "muted_trumpet",
  oboe: "oboe",
  ocarina: "ocarina",
  orchestra_hit: "orchestra_hit",
  orchestral_harp: "orchestral_harp",
  overdriven_guitar: "overdriven_guitar",
  pad_1_new_age: "pad_1_new_age",
  pad_2_warm: "pad_2_warm",
  pad_3_polysynth: "pad_3_polysynth",
  pad_4_choir: "pad_4_choir",
  pad_5_bowed: "pad_5_bowed",
  pad_6_metallic: "pad_6_metallic",
  pad_7_halo: "Pad 7 Halo",
  pad_8_sweep: "Pad 8 Sweep",
  pan_flute: "Pan Flute",
  percussive_organ: "Percussive Organ",
  piccolo: "Piccolo",
  pizzicato_strings: "Pizzicato Strings",
  recorder: "Recorder",
  reed_organ: "Reed Organ",
  reverse_cymbal: "Reverse Cymbal",
  rock_organ: "Rock Organ",
  seashore: "Seashore",
  shakuhachi: "Shakuhachi",
  shamisen: "Shamisen",
  shanai: "Shanai",
  sitar: "Sitar",
  slap_bass_1: "Slap Bass 1",
  slap_bass_2: "Slap Bass 2",
  soprano_sax: "Soprano Sax",
  steel_drums: "Steel Drums",
  string_ensemble_1: "String Ensemble 1",
  string_ensemble_2: "String Ensemble 2",
  synth_bass_1: "Synth Bass 1",
  synth_bass_2: "Synth Bass 2",
  synth_brass_1: "Synth Brass 1",
  synth_brass_2: "Synth Brass 2",
  synth_choir: "Synth Choir",
  synth_drum: "Synth Drum",
  synth_strings_1: "Synth Strings 1",
  synth_strings_2: "Synth Strings 2",
  taiko_drum: "Taiko Drum",
  tango_accordion: "Tango Accordion",
  telephone_ring: "Telephone Ring",
  tenor_sax: "Tenor Sax",
  timpani: "Timpani",
  tinkle_bell: "Tinkle Bell",
  tremolo_strings: "Tremolo Strings",
  trombone: "Trombone",
  trumpet: "Trumpet",
  tuba: "Tuba",
  tubular_bells: "Tubular Bells",
  vibraphone: "Vibraphone",
  viola: "Viola",
  violin: "Violin",
  voice_oohs: "Voice (Oohs)",
  whistle: "Whistle",
  woodblock: "Woodblock",
  xylophone: "Xylophone",
};
