import type { InstrumentName } from "soundfont-player";

export const Instruments: Record<InstrumentName, string> = {
  accordion: "Accordion",
  acoustic_bass: "Acoustic Bass",
  acoustic_grand_piano: "Acoustic Grand Piano",
  acoustic_guitar_nylon: "Acoustic Nylon Guitar",
  acoustic_guitar_steel: "Acoustic Steel Guitar",
  agogo: "Agogo",
  alto_sax: "Alto Sax",
  applause: "Applause",
  bagpipe: "Bagpipe",
  banjo: "Banjo",
  baritone_sax: "Baritone Sax",
  bassoon: "Bassoon",
  bird_tweet: "Bird Tweet",
  blown_bottle: "Blown Bottle",
  brass_section: "Brass Section",
  breath_noise: "Breath Noise",
  bright_acoustic_piano: "Bright Acoustic Piano",
  celesta: "Celesta",
  cello: "Cello",
  choir_aahs: "Choir (Aahs)",
  church_organ: "Church Organ",
  clarinet: "Clarinet",
  clavinet: "Clavinet",
  contrabass: "Contrabass",
  distortion_guitar: "Distortion Guitar",
  drawbar_organ: "Drawbar Organ",
  dulcimer: "Dulcimer",
  electric_bass_finger: "Electric Bass (Finger)",
  electric_bass_pick: "Electric Bass (Pick)",
  electric_grand_piano: "Electric Grand Piano",
  electric_guitar_clean: "Electric Guitar (Clean)",
  electric_guitar_jazz: "Electric Guitar (Jazz)",
  electric_guitar_muted: "Electric Guitar (Muted)",
  electric_piano_1: "Electric Piano 1",
  electric_piano_2: "Electric Piano 2",
  english_horn: "English Horn",
  fiddle: "Fiddle",
  flute: "Flute",
  french_horn: "French Horn",
  fretless_bass: "Fretless Bass",
  fx_1_rain: "FX 1 (Rain)",
  fx_2_soundtrack: "FX 2 (Soundtrack)",
  fx_3_crystal: "FX 3 (Crystal)",
  fx_4_atmosphere: "FX 4 (Atmosphere)",
  fx_5_brightness: "FX 5 (Brightness)",
  fx_6_goblins: "FX 6 (Goblins)",
  fx_7_echoes: "FX 7 (Echoes)",
  fx_8_scifi: "FX 8 (Sci-fi)",
  glockenspiel: "Glockenspiel",
  guitar_fret_noise: "Guitar Fret Noise",
  guitar_harmonics: "Guitar Harmonics",
  gunshot: "Gunshot",
  harmonica: "Harmonica",
  harpsichord: "Harpsichord",
  helicopter: "Helicopter",
  honkytonk_piano: "Honkytonk Piano",
  kalimba: "Kalimba",
  koto: "Koto",
  lead_1_square: "Lead 1 (Square)",
  lead_2_sawtooth: "Lead 2 (Sawtooth)",
  lead_3_calliope: "Lead 3 (Calliope)",
  lead_4_chiff: "Lead 4 (Chiff)",
  lead_5_charang: "Lead 5 (Charang)",
  lead_6_voice: "Lead 6 (Voice)",
  lead_7_fifths: "Lead 7 (Fifths)",
  lead_8_bass__lead: "Lead 8 (Bass - Lead)",
  marimba: "Marimba",
  melodic_tom: "Melodic Tom",
  music_box: "Music Box",
  muted_trumpet: "Muted Trumpet",
  oboe: "Oboe",
  ocarina: "Ocarina",
  orchestra_hit: "Orchestra Hit",
  orchestral_harp: "Orchestral Harp",
  overdriven_guitar: "Overdriven Guitar",
  pad_1_new_age: "Pad 1 (New age)",
  pad_2_warm: "Pad 2 (Warm)",
  pad_3_polysynth: "Pad 3 (Polysynth)",
  pad_4_choir: "Pad 4 (Choir)",
  pad_5_bowed: "Pad 5 (Bowed)",
  pad_6_metallic: "Pad 6 (Metallic)",
  pad_7_halo: "Pad 7 (Halo)",
  pad_8_sweep: "Pad 8 (Sweep)",
  pan_flute: "Pan Flute",
  percussive_organ: "Percussive Organ",
  piccolo: "Piccolo",
  pizzicato_strings: "Pizzicato Strings",
  recorder: "Recorder",
  reed_organ: "Reed Organ",
  reverse_cymbal: "Reverse Cymbal",
  rock_organ: "Rock Organ",
  seashore: "Seashore",
  shakuhachi: "Shakuhachi",
  shamisen: "Shamisen",
  shanai: "Shanai",
  sitar: "Sitar",
  slap_bass_1: "Slap Bass 1",
  slap_bass_2: "Slap Bass 2",
  soprano_sax: "Soprano Sax",
  steel_drums: "Steel Drums",
  string_ensemble_1: "String Ensemble 1",
  string_ensemble_2: "String Ensemble 2",
  synth_bass_1: "Synth Bass 1",
  synth_bass_2: "Synth Bass 2",
  synth_brass_1: "Synth Brass 1",
  synth_brass_2: "Synth Brass 2",
  synth_choir: "Synth Choir",
  synth_drum: "Synth Drum",
  synth_strings_1: "Synth Strings 1",
  synth_strings_2: "Synth Strings 2",
  taiko_drum: "Taiko Drum",
  tango_accordion: "Tango Accordion",
  telephone_ring: "Telephone Ring",
  tenor_sax: "Tenor Sax",
  timpani: "Timpani",
  tinkle_bell: "Tinkle Bell",
  tremolo_strings: "Tremolo Strings",
  trombone: "Trombone",
  trumpet: "Trumpet",
  tuba: "Tuba",
  tubular_bells: "Tubular Bells",
  vibraphone: "Vibraphone",
  viola: "Viola",
  violin: "Violin",
  voice_oohs: "Voice (Oohs)",
  whistle: "Whistle",
  woodblock: "Woodblock",
  xylophone: "Xylophone",
};
